<?php

namespace Space\Core\Modules\WPMLTranslate;

defined( 'ABSPATH' ) || exit;

use DOMDocument;
use DOMElement;
use DOMXPath;
use WP_Error;

class PayloadExtractor {

	public function extract( int $jobId, Repository $repository ): array|WP_Error {
		$job = $repository->find_job( $jobId );

		if ( ! $job ) {
			return new WP_Error(
				'wpml_translate_job_not_found',
				__( 'The requested WPML translation job was not found.', 'space-core' ),
				[ 'status' => 404, 'job_id' => $jobId ]
			);
		}

		$readiness = $repository->get_payload_readiness( $job );

		if ( ! $readiness['available'] ) {
			return [
				'module'         => 'WPMLTranslate',
				'job'            => $job,
				'payload_ready'  => false,
				'reason_code'    => $readiness['reason_code'],
				'reason_message' => $readiness['reason_message'],
				'raw_xliff'      => null,
				'units'          => [],
			];
		}

		if ( ! function_exists( 'wpml_tm_get_job_xliff' ) ) {
			return [
				'module'         => 'WPMLTranslate',
				'job'            => $job,
				'payload_ready'  => false,
				'reason_code'    => 'missing_wpml_tm_runtime',
				'reason_message' => __( 'WPML Translation Management XLIFF export helpers are unavailable.', 'space-core' ),
				'raw_xliff'      => null,
				'units'          => [],
			];
		}

		$xliff = $this->get_job_xliff( $jobId );

		if ( '' === $xliff ) {
			return [
				'module'         => 'WPMLTranslate',
				'job'            => $job,
				'payload_ready'  => false,
				'reason_code'    => 'empty_xliff',
				'reason_message' => __( 'WPML did not return exportable XLIFF for this job.', 'space-core' ),
				'raw_xliff'      => null,
				'units'          => [],
			];
		}

		$parsed = $this->parse_xliff( $xliff );
		if ( isset( $parsed['error'] ) ) {
			return [
				'module'         => 'WPMLTranslate',
				'job'            => $job,
				'payload_ready'  => false,
				'reason_code'    => 'invalid_xliff',
				'reason_message' => $parsed['error'],
				'raw_xliff'      => $xliff,
				'units'          => [],
			];
		}

		return [
			'module'          => 'WPMLTranslate',
			'payload_ready'   => true,
			'job'             => $job,
			'job_metadata'    => $parsed['job_metadata'],
			'source_language' => $parsed['source_language'] ?: $job['source_language'],
			'target_language' => $parsed['target_language'] ?: $job['target_language'],
			'unit_count'      => count( $parsed['units'] ),
			'units'           => $parsed['units'],
			'raw_xliff'       => $xliff,
		];
	}

	private function get_job_xliff( int $jobId ): string {
		try {
			$xliff = wpml_tm_get_job_xliff( $jobId, false );
		} catch ( \ArgumentCountError ) {
			$xliff = wpml_tm_get_job_xliff( $jobId );
		} catch ( \Throwable ) {
			return '';
		}

		return is_string( $xliff ) ? $xliff : '';
	}

	private function parse_xliff( string $xliff ): array {
		$previous = libxml_use_internal_errors( true );
		$dom      = new DOMDocument();
		$loaded   = $dom->loadXML( $xliff );
		$errors   = libxml_get_errors();
		libxml_clear_errors();
		libxml_use_internal_errors( $previous );

		if ( ! $loaded ) {
			$message = __( 'Failed to parse the XLIFF generated by WPML.', 'space-core' );
			if ( ! empty( $errors ) && isset( $errors[0]->message ) ) {
				$message = trim( $errors[0]->message );
			}

			return [ 'error' => $message ];
		}

		$xpath = new DOMXPath( $dom );
		$xpath->registerNamespace( 'x', 'urn:oasis:names:tc:xliff:document:1.2' );
		$xpath->registerNamespace( 'tool', 'urn:wpml:xliff:tool' );

		$file = $xpath->query( '/x:xliff/x:file' )->item( 0 );

		$units = [];
		foreach ( $xpath->query( '//x:trans-unit' ) as $unitNode ) {
			if ( ! $unitNode instanceof DOMElement ) {
				continue;
			}

			$sourceNode = $xpath->query( './x:source', $unitNode )->item( 0 );
			$targetNode = $xpath->query( './x:target', $unitNode )->item( 0 );

			$units[] = [
				'field_id'   => $unitNode->getAttribute( 'id' ),
				'source'     => $sourceNode ? trim( $sourceNode->textContent ) : '',
				'target'     => $targetNode ? trim( $targetNode->textContent ) : null,
				'metadata'   => [
					'resname'        => $unitNode->getAttribute( 'resname' ),
					'restype'        => $unitNode->getAttribute( 'restype' ),
					'datatype'       => $unitNode->getAttribute( 'datatype' ),
					'translate'      => $unitNode->getAttribute( 'translate' ),
					'wrap_tag'       => $unitNode->hasAttributeNS( 'urn:wpml:xliff:tool', 'wrap_tag' ) ? $unitNode->getAttributeNS( 'urn:wpml:xliff:tool', 'wrap_tag' ) : '',
					'extradata'      => $unitNode->hasAttributeNS( 'urn:wpml:xliff:tool', 'extradata' ) ? $unitNode->getAttributeNS( 'urn:wpml:xliff:tool', 'extradata' ) : '',
					'source_format'  => $sourceNode instanceof DOMElement ? $sourceNode->getAttribute( 'datatype' ) : '',
					'target_state'   => $targetNode instanceof DOMElement ? $targetNode->getAttribute( 'state' ) : '',
				],
			];
		}

		return [
			'job_metadata'    => [
				'original'     => $file instanceof DOMElement ? $file->getAttribute( 'original' ) : '',
				'datatype'     => $file instanceof DOMElement ? $file->getAttribute( 'datatype' ) : '',
				'source'       => $file instanceof DOMElement ? $file->getAttribute( 'source-language' ) : '',
				'target'       => $file instanceof DOMElement ? $file->getAttribute( 'target-language' ) : '',
				'tool_id'      => $file instanceof DOMElement ? $file->getAttribute( 'tool-id' ) : '',
				'date'         => $file instanceof DOMElement ? $file->getAttribute( 'date' ) : '',
			],
			'source_language' => $file instanceof DOMElement ? $file->getAttribute( 'source-language' ) : '',
			'target_language' => $file instanceof DOMElement ? $file->getAttribute( 'target-language' ) : '',
			'units'           => $units,
		];
	}
}
